### PR TITLE
Remove hash routing at Fulcrum and Torque

### PR DESCRIPTION
**Pull request by Kharabet**

### CODE REVIEW

**Comment by sneg55** [comment]
something doesn't look right here: 

https://deploy-preview-149--bzx-fulcrum.netlify.com/trade - > 404 

https://deploy-preview-149--bzx-fulcrum.netlify.com/#/trade - > redirect than /trade 200

**Comment by Kharabet** [comment]
> something doesn't look right here:
> 
> https://deploy-preview-149--bzx-fulcrum.netlify.com/trade - > 404
> 
> https://deploy-preview-149--bzx-fulcrum.netlify.com/#/trade - > redirect than /trade 200

Its a known issue with Netlify and React Router. _redirect files should fix it.

**Comment by Kharabet** [comment]
https://app.netlify.com/sites/bzx-fulcrum/deploys/5e9604f2723aaf0007f9cce5
Fulcrum build were not finished yet

**Comment by Kharabet** [comment]
Will merge it to kovan_build branch to release non-hash routing feature on relaunch

**Pull request merged**
