### PR TITLE
Add links to staking and explorer

### PR DESCRIPTION
**Pull request by OlehX**
Update headers and footers at:
- Fulcrum landing page
- Torque landing page
- Fulcrum
- Torque
- Staking
- Explorer

### CODE REVIEW

**Comment by OlehX** [comment]
https://app.clubhouse.io/bzx1/story/503/add-link-to-explorer
https://app.clubhouse.io/bzx1/story/498/add-link-to-staking

**Comment by tomcbean** [comment]
Please fix the PR confict.

**Comment by tomcbean** [comment]
Please fix merge conflict.

**Comment by Kharabet** [comment]
Fulcrum dapp: added header link to Staking 
Torque dapp: added header link to Staking 
Explorer dapp: added header link to Staking  and footer link to Explorer
Staking dapp: added footer link to Explorer
Fulcrum landing: added header link to Staking  and footer link to Explorer
Torque landing: added header link to Staking  and footer link to Explorer

**Pull request merged**
