### PR TITLE
Fulcrum trade/lend forms adjustments

### PR DESCRIPTION
**Pull request by Kharabet**

### CODE REVIEW

**Comment by Kharabet** [comment]
BUY and SELL buttons are currently enabled for testing modals

**Comment by Kharabet** [comment]
- Add preloader to main Lend/trade forms' input
- Make TradeExpectedResult component static with preloader
- Add loremipsum text-field at the bottom of collateral selector
- Binded lend/trade forms to top on mobiles screens to prevent keypad overlapping

**Comment by Kharabet** [comment]
@sneg55 current version is a release candidate. Please review the form's UI and behavior.

**Comment by sneg55** [comment]
@tomcbean 
Buy buttons enabled in this branch for testing
But overall it's good to go.

**Pull request merged**
