### PR TITLE
Add env variable for alchemy provider for local development

### PR DESCRIPTION
**Pull request by Kharabet**

### CODE REVIEW

**Comment by AoDev** [comment]
@Kharabet Torque .env should be removed from the repo, no?

**Comment by Kharabet** [comment]
> @Kharabet Torque .env should be removed from the repo, no?

Oh. missed that it was excluded from `.gitignore` somehow earlier

**Comment by AoDev** [comment]
@Kharabet Also, we need to make sure that the variables that were in .env are available during our builds. I don't have access to the build process but I guess it's an env var in Netlify config.

**Comment by Kharabet** [comment]
> @Kharabet Also, we need to make sure that the variables that were in .env are available during our builds. I don't have access to the build process but I guess it's an env var in Netlify config.

Currently, the production alchemy key isn't hidden. It is still opensource. Maybe make sense regenerate it and put it to the Netlify env variable. @tomcbean what do you think?

**Pull request merged**
