### PR TITLE
fulcrum: improve sections menu with chart / positions / trade history

### PR DESCRIPTION
**Pull request by OlehX**

### CODE REVIEW

**Comment by OlehX** [comment]
https://app.clubhouse.io/bzx1/story/791/fulcrum-improve-sections-menu-with-chart-positions-trade-history

**Comment by AoDev** [comment]
@OlehX 

Thanks for the changes.
Small things:
* a border top should have been set on the chart container with the same gray color for wider screen. In small screen it's fine so there is no need to add a border.

* there should be a bit more space between the menu / tabs and the chart / content.

* Could we add back the blue underline for the tab selected? (it should not have been removed probably a misunderstanding )

I think you can just add these styles on active tab, same blue as number of open position.

```css
// pseudo code
// .trade-token-grid-tab__items .tab.active
border-bottom: 3px solid #276bfb;
border-radius: 2px;
```

Screenshot 2020-11-03 at 20 41 30
Screenshot 2020-11-03 at 20 45 37

**Comment by OlehX** [comment]
@AoDev updated

**Comment by AoDev** [comment]
@OlehX perfect : )

**Comment by Kharabet** [comment]
resolves #207

**Pull request merged**
