### PR TITLE
Update navigation

### PR DESCRIPTION
**Pull request by Diana-Kovalyova**
https://app.clubhouse.io/bzx1/story/1480/update-navigation

### CODE REVIEW

**Review by AoDev — CHANGES_REQUESTED** [review]
@Diana-Kovalyova Some of the app links in the header aren't opening in new tabs. (At least in Torque.) Please check that they all do.

**Comment by AoDev** [comment]
In explorer I'd suggest you put more space between the header links and the tabs.

image

**Comment by Diana-Kovalyova** [comment]
> In explorer I'd suggest you put more space between the header links and the tabs. (liquidation, stats)
> 
> image

I've fixed it.

**Comment by Kharabet** [comment]
> @Diana-Kovalyova Some of the app links in the header aren't opening in new tabs. (At least in Torque.) Please check that they all do.

From ticket description:
image

I also updated Staking Dashboard header. Removed external link icons and removed target="_blank".
So now all apps' headers behavior and look are more or less consistent

**Review by Kharabet — APPROVED** [review]
I checked this PR as well. Merging to development

**Pull request merged**
